### ISSUE TITLE
`trim` is not a function error after updating Typescript to 4.3

### ISSUE THREAD

**Issue by mheob** [hipstersmoothie/react-docgen-typescript-plugin#38]
After updating to `typescript@4.3.2` I get the following error when running `start-storybook -p 6006`:

```console
70% sealing React Docgen Typescript Plugin ~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:475
            var trimmedText = (tag.text || '').trim();
                                               ^
TypeError: (tag.text || "").trim is not a function
    at ~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:475:48
    at Array.forEach (<anonymous>)
    at Parser.getFullJsDocComment (~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:474:14)
    at Parser.findDocComment (~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:443:28)
    at ~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:406:38
    at Array.forEach (<anonymous>)
    at Parser.getPropsInfo (~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:402:27)
    at Parser.getComponentInfo (~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:187:30)
    at ~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:895:30
    at Array.forEach (<anonymous>)
    at ~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:894:20
    at Array.reduce (<anonymous>)
    at parseWithProgramProvider (~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:886:10)
    at Object.parseWithProgramProvider (~/projects/.../node_modules/react-docgen-typescript/lib/parser.js:75:20)
    at processModule (~/projects/.../node_modules/react-docgen-typescript-plugin/dist/plugin.js:18:34)
    at ~/projects/.../node_modules/react-docgen-typescript-plugin/dist/plugin.js:97:49
```

In `typescript@4.2.4` this error does not appear. Is there anything I can do to fix it?

**Comment by mheob** [comment]
Ohh. Sorry, duplicate.
See https://github.com/styleguidist/react-docgen-typescript/issues/356 for more details.
